const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGES: 'CHANGE_LANGUAGES',

    //admin
    GET_GENDER_START: 'GET_GENDER_START',
    GET_GENDER_SUCCESS: 'GET_GENDER_SUCCESS',
    GET_GENDER_FAILED: 'GET_GENDER_FAILED',

    GET_POSITION_START: 'GET_POSITION_START',
    GET_POSITION_SUCCESS: 'GET_POSITION_SUCCESS',
    GET_POSITION_FAILED: 'GET_POSITION_FAILED',

    GET_ROLE_START: 'GET_ROLE_START',
    GET_ROLE_SUCCESS: 'GET_ROLE_SUCCESS',
    GET_ROLE_FAILED: 'GET_ROLE_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    // doctor
    FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',
    FETCH_TOP_DOCTORS_FAILED: 'FETCH_TOP_DOCTORS_FAILED',

    GET_ALL_DOCTORS_SUCCESS: 'GET_ALL_DOCTORS_SUCCESS',
    GET_ALL_DOCTORS_FAILED: 'GET_ALL_DOCTORS_FAILED',

    SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
    SAVE_DETAIL_DOCTOR_FAILED: 'SAVE_DETAIL_DOCTOR_FAILED',

    GET_INFO_DOCTOR_BY_ID_SUCCESS: 'GET_INFO_DOCTOR_BY_ID_SUCCESS',
    GET_INFO_DOCTOR_BY_ID_FAILED: 'GET_INFO_DOCTOR_BY_ID_FAILED',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
})

export default actionTypes;